=== kevin-allard/lesson-page/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "overview_type": { "type": "string", "enum": ["concept", "re_engagement"], "default": "concept" },
    "overview_pacing": {
      "type": "object",
      "properties": {
        "pacing_type": { "type": "string", "enum": ["hours", "minutes", "days"], "default": "minutes" },
        "pacing_amount": { "type": "integer" }
      },
      "required": ["pacing_amount"]
    },
    "overview_labels": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "overview_label_type": { "type": "string", "enum": ["basic", "session"], "default": "basic" },
          "overview_label_prefix": { "type": "string" },
          "overview_label_title": { "type": "string" }
        },
        "required": ["overview_label_title"]
      }
    },
    "overview_metadata": {
      "type": "object",
      "properties": {
        "overview_title": { "type": "string" },
        "overview_subtitle": { "type": "string" },
        "overview_description": { "type": "string" },
        "overview_number": { "type": "integer" }
      },
      "additionalProperties": true
    },
    "overview_items": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "overview_item_type": { "type": "string", "enum": ["basic", "big_ideas", "learning_goals", "essential_ideas", "key_terms", "pacing_guide", "materials_needed"], "default": "basic" },
          "overview_item_title": { "type": "string" },
          "overview_item_data": {
            "type": "object",
            "properties": {
              "overview_item_data_type": { "type": "string", "enum": ["list", "group_list", "session_list"], "default": "list" },
              "overview_item_data_items": {
                "type": "array",
                "items": { "type": "string" }
              },
              "overview_item_data_groups": {
                "type": "array",
                "items": {
                  "$ref": "#/definitions/dataGroup"
                }
              }
            }
          }
        },
        "required": ["overview_item_data"]
      }
    }
  },
  "required": ["overview_pacing", "overview_items"],
  "definitions": {
    "dataGroup": {
      "type": "object",
      "properties": {
        "overview_item_data_group_title": { "type": "string" },
        "overview_item_data_group_items": {
          "type": "array",
          "items": {
            "anyOf": [
              { "type": "string" },
              { "$ref": "#/definitions/dataGroup" },
              { "$ref": "#/definitions/pacingActivity" }
            ]
          }
        }
      },
      "required": ["overview_item_data_group_title", "overview_item_data_group_items"]
    },
    "pacingActivity": {
      "type": "object",
      "properties": {
        "overview_item_data_group_item_type": { "type": "string", "enum": ["none", "book", "online", "presentation"], "default": "none" },
        "overview_item_data_group_item_prefix": { "type": "string" },
        "overview_item_data_group_item_title": { "type": "string" },
        "overview_item_data_group_item_description": { "type": "string" },
        "overview_item_data_group_item_pacing": {
          "type": "object",
          "properties": {
            "pacing_type": { "type": "string", "enum": ["hours", "minutes", "days"], "default": "minutes" },
            "pacing_amount": { "type": "integer" }
          },
          "required": ["pacing_amount"]
        }
      },
      "required": ["overview_item_data_group_item_title", "overview_item_data_group_item_description"]
    }
  }
}

=== kevin-allard/lesson-page/data/CA_SM5e_G06_TIG_M01_T01_L07.json
{
  "overview_type": "concept",
  "overview_pacing": {
    "pacing_type": "minutes",
    "pacing_amount": 90
  },
  "overview_labels": [
    {
      "overview_label_type": "session",
      "overview_label_prefix": "2",
      "overview_label_title": "Sessions"
    }
  ],
  "overview_metadata": {
    "overview_number": 7,
    "overview_title": "I'd Divide",
    "overview_subtitle": "Modeling Fraction Division",
    "overview_description": "In this lesson, students use fraction strips and number line models to investigate the division of fractions by fractions. They use these models to develop an algorithm for rewriting division sentences as multiplication sentences. Students then apply the procedure to solve problems involving fractions and mixed numbers."
  },
  "overview_items": [
    {
      "overview_item_type": "learning_goals",
      "overview_item_title": "My Learning Goals",
      "overview_item_data": {
        "overview_item_data_type": "list",
        "overview_item_data_items": [
          "I can model the division of fractions using pictures, bar models, and number lines.",
          "I can interpret and compute quotients of fractions."
        ]
      }
    },
    {
      "overview_item_type": "big_ideas",
      "overview_item_title": "Big Idea",
      "overview_item_data": {
        "overview_item_data_type": "list",
        "overview_item_data_items": [
          "Fraction Relationships"
        ]
      }
    },
    {
      "overview_item_type": "essential_ideas",
      "overview_item_title": "Essential Ideas",
      "overview_item_data": {
        "overview_item_data_type": "list",
        "overview_item_data_items": [
          "You can use area models and fact families to illustrate the quotients of fractions.",
          "The reciprocal or multiplicative inverse of a number <math><mfrac><mi>a</mi><mi>b</mi></mfrac></math> is the number <math><mfrac><mi>b</mi><mi>a</mi></mfrac></math>, where <math><mi>a</mi></math> and <math><mi>b</mi></math> are nonzero numbers.",
          "To calculate the quotient of two fractions, multiply the dividend by the reciprocal of the divisor."
        ]
      }
    },
    {
      "overview_item_type": "key_terms",
      "overview_item_title": "Key Terms",
      "overview_item_data": {
        "overview_item_data_type": "group_list",
        "overview_item_data_groups": [
          {
            "overview_item_data_group_title": "Activity 3",
            "overview_item_data_group_items": [
              "reciprocal",
              "multiplicative inverse"
            ]
          }
        ]
      }
    },
    {
      "overview_item_type": "pacing_guide",
      "overview_item_title": "Lesson Structure and Pacing Guide",
      "overview_item_data": {
        "overview_item_data_type": "session_list",
        "overview_item_data_groups": [
          {
            "overview_item_data_group_title": "Session 1",
            "overview_item_data_group_items": [
              {
                "overview_item_data_group_title": "Activate",
                "overview_item_data_group_items": [
                  {
                    "overview_item_data_group_item_type": "presentation",
                    "overview_item_data_group_item_title": "All in the Fact Family",
                    "overview_item_data_group_item_description": "Students identify an equation that is part of a multiplication-division fact family given an area model.",
                    "overview_item_data_group_item_pacing": { "pacing_type": "minutes", "pacing_amount": 5 }
                  }
                ]
              },
              {
                "overview_item_data_group_title": "Explore and Develop",
                "overview_item_data_group_items": [
                  {
                    "overview_item_data_group_item_type": "book",
                    "overview_item_data_group_item_prefix": "Activity 1",
                    "overview_item_data_group_item_title": "Whole Number รท Fraction",
                    "overview_item_data_group_item_description": "Students investigate the division of whole numbers by fractions.",
                    "overview_item_data_group_item_pacing": { "pacing_type": "minutes", "pacing_amount": 35 }
                  }
                ]
              }
            ]
          },
          {
            "overview_item_data_group_title": "Session 2",
            "overview_item_data_group_items": [
              {
                "overview_item_data_group_title": "Explore and Develop",
                "overview_item_data_group_items": [
                  {
                    "overview_item_data_group_item_type": "book",
                    "overview_item_data_group_item_prefix": "Activity 2",
                    "overview_item_data_group_item_title": "Fraction รท Fraction",
                    "overview_item_data_group_item_description": "Students investigate the division of fractions by fractions.",
                    "overview_item_data_group_item_pacing": { "pacing_type": "minutes", "pacing_amount": 15 }
                  },
                  {
                    "overview_item_data_group_item_type": "online",
                    "overview_item_data_group_item_prefix": "Activity 3",
                    "overview_item_data_group_item_title": "Moving from the Model to a Procedure",
                    "overview_item_data_group_item_description": "Students develop an algorithm to rewrite division sentences as multiplication sentences.",
                    "overview_item_data_group_item_pacing": { "pacing_type": "minutes", "pacing_amount": 20 }
                  }
                ]
              },
              {
                "overview_item_data_group_title": "Reflect",
                "overview_item_data_group_items": [
                  {
                    "overview_item_data_group_item_type": "book",
                    "overview_item_data_group_item_title": "A Vision of Division",
                    "overview_item_data_group_item_description": "Students apply the fraction division algorithm to solve real-world situations.",
                    "overview_item_data_group_item_pacing": { "pacing_type": "minutes", "pacing_amount": 5 }
                  }
                ]
              }
            ]
          }
        ]
      }
    },
    {
      "overview_item_type": "materials_needed",
      "overview_item_title": "Materials Needed",
      "overview_item_data": {
        "overview_item_data_type": "list",
        "overview_item_data_items": [
          "If facilitating this lesson without student devices, no additional materials are needed.",
          "To avoid printing additional materials not included in MATHbook (like Activate activities and Session Quick Checks) project them using the Present button above."
        ]
      }
    }
  ]
}
